// Note: This file is automatically generated
//       It will be overwritten when testing

import Testing
@testable import NumberTranslator

@Test func ArabicNumerals() {
    let translator = ArabicNumeralsImplementation()
    #expect(translator.translate(0).x == "٠")
    #expect(translator.translate(1).x == "١")
    #expect(translator.translate(2).x == "٢")
    #expect(translator.translate(3).x == "٣")
    #expect(translator.translate(4).x == "٤")
    #expect(translator.translate(5).x == "٥")
    #expect(translator.translate(6).x == "٦")
    #expect(translator.translate(7).x == "٧")
    #expect(translator.translate(8).x == "٨")
    #expect(translator.translate(9).x == "٩")
    #expect(translator.translate(10).x == "١٠")
    #expect(translator.translate(11).x == "١١")
    #expect(translator.translate(12).x == "١٢")
    #expect(translator.translate(13).x == "١٣")
    #expect(translator.translate(14).x == "١٤")
    #expect(translator.translate(114).x == "١١٤")
    #expect(translator.translate(114.7).x == "١١٤.٧")
    #expect(translator.translate(1_147).x == "١١٤٧")
    #expect(translator.translate(1_000).x == "١٠٠٠")
    #expect(translator.translate(-1).x == "-١")
    #expect(translator.translate(1.3).x == "١.٣")
}
