// Note: This file is automatically generated
//       It will be overwritten when testing

import Testing
@testable import NumberTranslator

@Test func ArabicNumerals() {
    let translator = NumberTranslator()
    #expect(translator.translate(0, to: .arabicNumerals).x == "٠")
    #expect(translator.translate(1, to: .arabicNumerals).x == "١")
    #expect(translator.translate(2, to: .arabicNumerals).x == "٢")
    #expect(translator.translate(3, to: .arabicNumerals).x == "٣")
    #expect(translator.translate(4, to: .arabicNumerals).x == "٤")
    #expect(translator.translate(5, to: .arabicNumerals).x == "٥")
    #expect(translator.translate(6, to: .arabicNumerals).x == "٦")
    #expect(translator.translate(7, to: .arabicNumerals).x == "٧")
    #expect(translator.translate(8, to: .arabicNumerals).x == "٨")
    #expect(translator.translate(9, to: .arabicNumerals).x == "٩")
    #expect(translator.translate(10, to: .arabicNumerals).x == "١٠")
    #expect(translator.translate(11, to: .arabicNumerals).x == "١١")
    #expect(translator.translate(12, to: .arabicNumerals).x == "١٢")
    #expect(translator.translate(13, to: .arabicNumerals).x == "١٣")
    #expect(translator.translate(14, to: .arabicNumerals).x == "١٤")
    #expect(translator.translate(114, to: .arabicNumerals).x == "١١٤")
    #expect(translator.translate(114.7, to: .arabicNumerals).x == "١١٤.٧")
    #expect(translator.translate(1_147, to: .arabicNumerals).x == "١١٤٧")
    #expect(translator.translate(1_000, to: .arabicNumerals).x == "١٠٠٠")
    #expect(translator.translate(-1, to: .arabicNumerals).x == "-١")
    #expect(translator.translate(1.3, to: .arabicNumerals).x == "١.٣")
}
