// Note: This file is automatically generated by the python script Tests/testsFromGroundtruth.py
//       Running this script will be overwrite any changes you make to this file

import Testing
@testable import NumberTranslator

@Test func ArmenianNumerals() {
    let translator = NumberTranslator()
    #expect(translator.translate(0, to: .armenianNumerals).x == "zero unknown")
    #expect(translator.translate(1, to: .armenianNumerals).x == "Ա")
    #expect(translator.translate(2, to: .armenianNumerals).x == "Բ")
    #expect(translator.translate(3, to: .armenianNumerals).x == "Գ")
    #expect(translator.translate(4, to: .armenianNumerals).x == "Դ")
    #expect(translator.translate(5, to: .armenianNumerals).x == "Ե")
    #expect(translator.translate(6, to: .armenianNumerals).x == "Զ")
    #expect(translator.translate(7, to: .armenianNumerals).x == "Է")
    #expect(translator.translate(8, to: .armenianNumerals).x == "Ը")
    #expect(translator.translate(9, to: .armenianNumerals).x == "Թ")
    #expect(translator.translate(10, to: .armenianNumerals).x == "Ժ")
    #expect(translator.translate(11, to: .armenianNumerals).x == "ԺԱ")
    #expect(translator.translate(12, to: .armenianNumerals).x == "ԺԲ")
    #expect(translator.translate(13, to: .armenianNumerals).x == "ԺԳ")
    #expect(translator.translate(14, to: .armenianNumerals).x == "ԺԴ")
    #expect(translator.translate(50, to: .armenianNumerals).x == "Ծ")
    #expect(translator.translate(120, to: .armenianNumerals).x == "ՃԻ")
    #expect(translator.translate(1975, to: .armenianNumerals).x == "ՌՋՀԵ")
    #expect(translator.translate(2004, to: .armenianNumerals).x == "ՍԴ")
    #expect(translator.translate(2_222, to: .armenianNumerals).x == "ՍՄԻԲ")
    #expect(translator.translate(9_999, to: .armenianNumerals).x == "ՔՋՂԹ")
    #expect(translator.translate(10_000, to: .armenianNumerals).x == "Ա_OVERLINE_")
    #expect(translator.translate(9_000_000, to: .armenianNumerals).x == "Ջ_OVERLINE_")
    #expect(translator.translate(11_431_255, to: .armenianNumerals).x == "ՌՃԽԳ_OVERLINE_ՌՄԾԵ")

    let temp1 = 11_43*10_000+1_255
    #expect(translator.translate(temp1, to: .armenianNumerals).x == "ՌՃԽԳ_OVERLINE_ՌՄԾԵ")

    let temp2 = 9_999*10_000+9_999
    #expect(translator.translate(temp2, to: .armenianNumerals).x == "ՔՋՂԹ_OVERLINE_ՔՋՂԹ")

    let temp3 = 9_999*10_000+9_999+1
    #expect(translator.translate(temp3, to: .armenianNumerals).x == "too large")
}
