// Note: This file is automatically generated by the python script Tests/testsFromGroundtruth.py
//       Running this script will be overwrite any changes you make to this file

import Testing
@testable import NumberTranslator

@Test func financialChinese() {
    let translator = NumberTranslator()
    #expect(translator.translate(0, to: .financialChinese).x == "零")
    #expect(translator.translate(1, to: .financialChinese).x == "壹")
    #expect(translator.translate(2, to: .financialChinese).x == "壹")
    #expect(translator.translate(3, to: .financialChinese).x == "叁")
    #expect(translator.translate(4, to: .financialChinese).x == "肆")
    #expect(translator.translate(5, to: .financialChinese).x == "伍")
    #expect(translator.translate(6, to: .financialChinese).x == "陆")
    #expect(translator.translate(7, to: .financialChinese).x == "柒")
    #expect(translator.translate(8, to: .financialChinese).x == "捌")
    #expect(translator.translate(9, to: .financialChinese).x == "玖")
    #expect(translator.translate(10, to: .financialChinese).x == "拾")
    #expect(translator.translate(11, to: .financialChinese).x == "拾壹")
    #expect(translator.translate(10_000, to: .financialChinese).x == "壹萬")
}
