// Note: This file is automatically generated
//       It will be overwritten when testing

import Testing
@testable import NumberTranslator

@Test func Hieroglyphs() {
    let translator = HieroglyphsImplementation()
    #expect(translator.translate(0).x == "zero unknown")
    #expect(translator.translate(1).x == translator.symbolOne)
    #expect(translator.translate(2).x == translator.symbolOne+translator.symbolOne)
    #expect(translator.translate(3).x == translator.symbolOne+translator.symbolOne+translator.symbolOne)
    #expect(translator.translate(10).x == translator.symbolTen)
    #expect(translator.translate(100).x == translator.symbolHundred)
    #expect(translator.translate(1_000).x == translator.symbolThousand)
    #expect(translator.translate(4_122).x == translator.symbolThousand+translator.symbolThousand+translator.symbolThousand+translator.symbolThousand+translator.symbolHundred+translator.symbolTen+translator.symbolTen+translator.symbolOne+translator.symbolOne)
    #expect(translator.translate(4_002).x == translator.symbolThousand+translator.symbolThousand+translator.symbolThousand+translator.symbolThousand+translator.symbolOne+translator.symbolOne)
    #expect(translator.translate(10_000).x == translator.symbolTenThousand)
    #expect(translator.translate(100_000).x == translator.symbolHundredThousand)
    #expect(translator.translate(1_000_000).x == translator.symbolMillion)
}
