// Note: This file is automatically generated by the python script Tests/testsFromGroundtruth.py
//       Running this script will be overwrite any changes you make to this file

import Testing
@testable import NumberTranslator

@Test func Hieroglyphs() {
    let translator = NumberTranslator()
    let symbolOne = "\u{133E4}"
    let symbolTen = "\u{13386}"
    let symbolHundred = "\u{13362}"
    let symbolThousand = "\u{131BC}"
    let symbolTenThousand = "\u{130AD}"
    let symbolHundredThousand = "\u{13190}"
    let symbolMillion = "\u{13068}"
    #expect(translator.translate(0, to: .hieroglyphs).x == "zero unknown")
    #expect(translator.translate(1, to: .hieroglyphs).x == symbolOne)
    #expect(translator.translate(2, to: .hieroglyphs).x == symbolOne+symbolOne)
    #expect(translator.translate(3, to: .hieroglyphs).x == symbolOne+symbolOne+symbolOne)
    #expect(translator.translate(10, to: .hieroglyphs).x == symbolTen)
    #expect(translator.translate(100, to: .hieroglyphs).x == symbolHundred)
    #expect(translator.translate(1_000, to: .hieroglyphs).x == symbolThousand)
    #expect(translator.translate(4_122, to: .hieroglyphs).x == symbolThousand+symbolThousand+symbolThousand+symbolThousand+symbolHundred+symbolTen+symbolTen+symbolOne+symbolOne)
    #expect(translator.translate(4_002, to: .hieroglyphs).x == symbolThousand+symbolThousand+symbolThousand+symbolThousand+symbolOne+symbolOne)
    #expect(translator.translate(10_000, to: .hieroglyphs).x == symbolTenThousand)
    #expect(translator.translate(100_000, to: .hieroglyphs).x == symbolHundredThousand)
    #expect(translator.translate(1_000_000, to: .hieroglyphs).x == symbolMillion)
}
