// Note: This file is automatically generated
//       It will be overwritten when testing

import Testing
@testable import NumberTranslator

@Test func Hindi() {
    let translator = HindiImplementation()
    #expect(translator.translate(0).x == "शून्य")
    #expect(translator.translate(1).x == "एक")
    #expect(translator.translate(2).x == "दो")
    #expect(translator.translate(3).x == "तीन")
    #expect(translator.translate(4).x == "चार")
    #expect(translator.translate(5).x == "पांच")
    #expect(translator.translate(6).x == "छः")
    #expect(translator.translate(7).x == "सात")
    #expect(translator.translate(8).x == "आठ")
    #expect(translator.translate(9).x == "नौ")
    #expect(translator.translate(10).x == "दश")
    #expect(translator.translate(11).x == "ग्यारह")
    #expect(translator.translate(12).x == "बारह")
    #expect(translator.translate(13).x == "तेरह")
    #expect(translator.translate(14).x == "चौदह")
    #expect(translator.translate(15).x == "पंद्रह")
    #expect(translator.translate(16).x == "सोलह")
    #expect(translator.translate(17).x == "सत्रह")
    #expect(translator.translate(18).x == "अट्ठारह")
    #expect(translator.translate(19).x == "उन्नीस")
    #expect(translator.translate(20).x == "बीस")
    #expect(translator.translate(21).x == "इक्कीस")
    #expect(translator.translate(22).x == "बाईस")
    #expect(translator.translate(23).x == "तेईस")
    #expect(translator.translate(24).x == "चौबिस")
    #expect(translator.translate(25).x == "पच्चीस")
    #expect(translator.translate(26).x == "छब्बीस")
    #expect(translator.translate(27).x == "सत्ताईस")
    #expect(translator.translate(28).x == "अट्ठाईस")
    #expect(translator.translate(29).x == "उनतीस")
    #expect(translator.translate(30).x == "तीस")
    #expect(translator.translate(31).x == "इकतीस")
    #expect(translator.translate(32).x == "बत्तीस")
    #expect(translator.translate(33).x == "तैंतीस")
    #expect(translator.translate(34).x == "चौंतीस")
    #expect(translator.translate(35).x == "पैंतीस")
    #expect(translator.translate(36).x == "छत्तीस")
    #expect(translator.translate(37).x == "सैंतीस")
    #expect(translator.translate(38).x == "अड़तीस")
    #expect(translator.translate(39).x == "उनतालीस")
    #expect(translator.translate(40).x == "चालीस")
    #expect(translator.translate(41).x == "इकतालीस")
    #expect(translator.translate(42).x == "बयालीस")
    #expect(translator.translate(43).x == "तैंतालीस")
    #expect(translator.translate(44).x == "चौंतालीस")
    #expect(translator.translate(45).x == "पैंतालीस")
    #expect(translator.translate(46).x == "छियालीस")
    #expect(translator.translate(47).x == "सैंतालीस")
    #expect(translator.translate(48).x == "अड़तालीस")
    #expect(translator.translate(49).x == "उनचास")
    #expect(translator.translate(50).x == "पचास")
    #expect(translator.translate(51).x == "इक्यावन")
    #expect(translator.translate(52).x == "बावन")
    #expect(translator.translate(53).x == "तिरपन")
    #expect(translator.translate(54).x == "चौवन")
    #expect(translator.translate(55).x == "पचपन")
    #expect(translator.translate(56).x == "छप्पन")
    #expect(translator.translate(57).x == "सत्तावन")
    #expect(translator.translate(58).x == "अट्ठावन")
    #expect(translator.translate(59).x == "उनसठ")
    #expect(translator.translate(60).x == "साठ")
    #expect(translator.translate(61).x == "इकसठ")
    #expect(translator.translate(62).x == "बासठ")
    #expect(translator.translate(63).x == "तिरसठ")
    #expect(translator.translate(64).x == "चौंसठ")
    #expect(translator.translate(65).x == "पैंसठ")
    #expect(translator.translate(66).x == "छयासठ")
    #expect(translator.translate(67).x == "सड़सठ")
    #expect(translator.translate(68).x == "अड़सठ")
    #expect(translator.translate(69).x == "उनहत्तर")
    #expect(translator.translate(70).x == "सत्तर")
    #expect(translator.translate(71).x == "इकहत्तर")
    #expect(translator.translate(72).x == "बहत्तर")
    #expect(translator.translate(73).x == "तिहत्तर")
    #expect(translator.translate(74).x == "चौहत्तर")
    #expect(translator.translate(75).x == "पचहत्तर")
    #expect(translator.translate(76).x == "छिहत्तर")
    #expect(translator.translate(77).x == "सतहत्तर")
    #expect(translator.translate(78).x == "अठहत्तर")
    #expect(translator.translate(79).x == "उनासी")
    #expect(translator.translate(80).x == "अस्सी")
    #expect(translator.translate(81).x == "इक्यासी")
    #expect(translator.translate(82).x == "बयासी")
    #expect(translator.translate(83).x == "तिरासी")
    #expect(translator.translate(84).x == "चौरासी")
    #expect(translator.translate(85).x == "पचासी")
    #expect(translator.translate(86).x == "छियासी")
    #expect(translator.translate(87).x == "सत्तासी")
    #expect(translator.translate(88).x == "अठासी")
    #expect(translator.translate(89).x == "नवासी")
    #expect(translator.translate(90).x == "नब्बे")
    #expect(translator.translate(91).x == "इक्यानवे")
    #expect(translator.translate(92).x == "बानवे")
    #expect(translator.translate(93).x == "तिरानवे")
    #expect(translator.translate(94).x == "चौरानवे")
    #expect(translator.translate(95).x == "पचानवे")
    #expect(translator.translate(96).x == "छियानवे")
    #expect(translator.translate(97).x == "सत्तानवे")
    #expect(translator.translate(98).x == "अट्ठानवे")
    #expect(translator.translate(99).x == "निन्यानवे")
    #expect(translator.translate(100).x == "एक सौ") // "सौ
    #expect(translator.translate(200).x == "दो सौ") // "सौ
    #expect(translator.translate(250).x == "दो सौ पचास") // दो सौ पचास
    #expect(translator.translate(300).x == "तीन सौ") // "सौ
    #expect(translator.translate(352).x == "तीन सौ बावन") // "सौ
    #expect(translator.translate(1000).x == "एक हज़ार") // / एक सहस्र

    let temp1 = 10*1000
    #expect(translator.translate(temp1).x == "दश हज़ार")

    let temp2 = 100*1000
    #expect(translator.translate(temp2).x == "एक लाख") // 1 Lakh

    let temp3 = 10*100*1000
    #expect(translator.translate(temp3).x == "दश लाख")
    #expect(translator.translate(1_000_000).x == "दश लाख")
    #expect(translator.translate(1_000_500).x == "दश लाख पांच सौ") // ? दश लाख पांच सौ

    let temp4 = 100*100*1000
    #expect(translator.translate(temp4).x == "एक करोड़") // 1 Crore
    #expect(translator.translate(10_000_000).x == "एक करोड़")

    let temp5 = 10*100*100_000
    #expect(translator.translate(temp5).x == "दश करोड़")
    #expect(translator.translate(100_000_000).x == "दश करोड़")

    let temp6 = 50*100*100_000
    #expect(translator.translate(temp6).x == "पचास करोड़")
    #expect(translator.translate(500_000_000).x == "पचास करोड़")

    let temp7 = 100*100*100*1000
    #expect(translator.translate(temp7).x == "एक अरब") // 1 Arab
    #expect(translator.translate(1_000_000_000).x == "एक अरब")

    let temp8 = 2*100*100*100*1000
    #expect(translator.translate(temp8).x == "दो अरब")

    let temp9 = 2*100*100*100*1000+50*100*100_000
    #expect(translator.translate(temp9).x == "दो अरब पचास करोड़") // दो अरब पचास करोड़
    #expect(translator.translate(2_500_000_000).x == "दो अरब पचास करोड़") // दो अरब पांच सौ करोड़
    #expect(translator.translate(10_000_000_000).x == "दश अरब")
    #expect(translator.translate(100_000_000_000).x == "एक खरब") // एक सौ अरब
    #expect(translator.translate(-1).x == "ऋण एक")
    #expect(translator.translate(1.3).x == "एक दशमलव तीन")
}
