// Note: This file is automatically generated by the python script Tests/testsFromGroundtruth.py
//       Running this script will be overwrite any changes you make to this file

import Testing
@testable import NumberTranslator

@Test func Hindi() {
    let translator = NumberTranslator()
    #expect(translator.translate(0, to: .hindi).x == "शून्य")
    #expect(translator.translate(1, to: .hindi).x == "एक")
    #expect(translator.translate(2, to: .hindi).x == "दो")
    #expect(translator.translate(3, to: .hindi).x == "तीन")
    #expect(translator.translate(4, to: .hindi).x == "चार")
    #expect(translator.translate(5, to: .hindi).x == "पांच")
    #expect(translator.translate(6, to: .hindi).x == "छः")
    #expect(translator.translate(7, to: .hindi).x == "सात")
    #expect(translator.translate(8, to: .hindi).x == "आठ")
    #expect(translator.translate(9, to: .hindi).x == "नौ")
    #expect(translator.translate(10, to: .hindi).x == "दश")
    #expect(translator.translate(11, to: .hindi).x == "ग्यारह")
    #expect(translator.translate(12, to: .hindi).x == "बारह")
    #expect(translator.translate(13, to: .hindi).x == "तेरह")
    #expect(translator.translate(14, to: .hindi).x == "चौदह")
    #expect(translator.translate(15, to: .hindi).x == "पंद्रह")
    #expect(translator.translate(16, to: .hindi).x == "सोलह")
    #expect(translator.translate(17, to: .hindi).x == "सत्रह")
    #expect(translator.translate(18, to: .hindi).x == "अट्ठारह")
    #expect(translator.translate(19, to: .hindi).x == "उन्नीस")
    #expect(translator.translate(20, to: .hindi).x == "बीस")
    #expect(translator.translate(21, to: .hindi).x == "इक्कीस")
    #expect(translator.translate(22, to: .hindi).x == "बाईस")
    #expect(translator.translate(23, to: .hindi).x == "तेईस")
    #expect(translator.translate(24, to: .hindi).x == "चौबिस")
    #expect(translator.translate(25, to: .hindi).x == "पच्चीस")
    #expect(translator.translate(26, to: .hindi).x == "छब्बीस")
    #expect(translator.translate(27, to: .hindi).x == "सत्ताईस")
    #expect(translator.translate(28, to: .hindi).x == "अट्ठाईस")
    #expect(translator.translate(29, to: .hindi).x == "उनतीस")
    #expect(translator.translate(30, to: .hindi).x == "तीस")
    #expect(translator.translate(31, to: .hindi).x == "इकतीस")
    #expect(translator.translate(32, to: .hindi).x == "बत्तीस")
    #expect(translator.translate(33, to: .hindi).x == "तैंतीस")
    #expect(translator.translate(34, to: .hindi).x == "चौंतीस")
    #expect(translator.translate(35, to: .hindi).x == "पैंतीस")
    #expect(translator.translate(36, to: .hindi).x == "छत्तीस")
    #expect(translator.translate(37, to: .hindi).x == "सैंतीस")
    #expect(translator.translate(38, to: .hindi).x == "अड़तीस")
    #expect(translator.translate(39, to: .hindi).x == "उनतालीस")
    #expect(translator.translate(40, to: .hindi).x == "चालीस")
    #expect(translator.translate(41, to: .hindi).x == "इकतालीस")
    #expect(translator.translate(42, to: .hindi).x == "बयालीस")
    #expect(translator.translate(43, to: .hindi).x == "तैंतालीस")
    #expect(translator.translate(44, to: .hindi).x == "चौंतालीस")
    #expect(translator.translate(45, to: .hindi).x == "पैंतालीस")
    #expect(translator.translate(46, to: .hindi).x == "छियालीस")
    #expect(translator.translate(47, to: .hindi).x == "सैंतालीस")
    #expect(translator.translate(48, to: .hindi).x == "अड़तालीस")
    #expect(translator.translate(49, to: .hindi).x == "उनचास")
    #expect(translator.translate(50, to: .hindi).x == "पचास")
    #expect(translator.translate(51, to: .hindi).x == "इक्यावन")
    #expect(translator.translate(52, to: .hindi).x == "बावन")
    #expect(translator.translate(53, to: .hindi).x == "तिरपन")
    #expect(translator.translate(54, to: .hindi).x == "चौवन")
    #expect(translator.translate(55, to: .hindi).x == "पचपन")
    #expect(translator.translate(56, to: .hindi).x == "छप्पन")
    #expect(translator.translate(57, to: .hindi).x == "सत्तावन")
    #expect(translator.translate(58, to: .hindi).x == "अट्ठावन")
    #expect(translator.translate(59, to: .hindi).x == "उनसठ")
    #expect(translator.translate(60, to: .hindi).x == "साठ")
    #expect(translator.translate(61, to: .hindi).x == "इकसठ")
    #expect(translator.translate(62, to: .hindi).x == "बासठ")
    #expect(translator.translate(63, to: .hindi).x == "तिरसठ")
    #expect(translator.translate(64, to: .hindi).x == "चौंसठ")
    #expect(translator.translate(65, to: .hindi).x == "पैंसठ")
    #expect(translator.translate(66, to: .hindi).x == "छयासठ")
    #expect(translator.translate(67, to: .hindi).x == "सड़सठ")
    #expect(translator.translate(68, to: .hindi).x == "अड़सठ")
    #expect(translator.translate(69, to: .hindi).x == "उनहत्तर")
    #expect(translator.translate(70, to: .hindi).x == "सत्तर")
    #expect(translator.translate(71, to: .hindi).x == "इकहत्तर")
    #expect(translator.translate(72, to: .hindi).x == "बहत्तर")
    #expect(translator.translate(73, to: .hindi).x == "तिहत्तर")
    #expect(translator.translate(74, to: .hindi).x == "चौहत्तर")
    #expect(translator.translate(75, to: .hindi).x == "पचहत्तर")
    #expect(translator.translate(76, to: .hindi).x == "छिहत्तर")
    #expect(translator.translate(77, to: .hindi).x == "सतहत्तर")
    #expect(translator.translate(78, to: .hindi).x == "अठहत्तर")
    #expect(translator.translate(79, to: .hindi).x == "उनासी")
    #expect(translator.translate(80, to: .hindi).x == "अस्सी")
    #expect(translator.translate(81, to: .hindi).x == "इक्यासी")
    #expect(translator.translate(82, to: .hindi).x == "बयासी")
    #expect(translator.translate(83, to: .hindi).x == "तिरासी")
    #expect(translator.translate(84, to: .hindi).x == "चौरासी")
    #expect(translator.translate(85, to: .hindi).x == "पचासी")
    #expect(translator.translate(86, to: .hindi).x == "छियासी")
    #expect(translator.translate(87, to: .hindi).x == "सत्तासी")
    #expect(translator.translate(88, to: .hindi).x == "अठासी")
    #expect(translator.translate(89, to: .hindi).x == "नवासी")
    #expect(translator.translate(90, to: .hindi).x == "नब्बे")
    #expect(translator.translate(91, to: .hindi).x == "इक्यानवे")
    #expect(translator.translate(92, to: .hindi).x == "बानवे")
    #expect(translator.translate(93, to: .hindi).x == "तिरानवे")
    #expect(translator.translate(94, to: .hindi).x == "चौरानवे")
    #expect(translator.translate(95, to: .hindi).x == "पचानवे")
    #expect(translator.translate(96, to: .hindi).x == "छियानवे")
    #expect(translator.translate(97, to: .hindi).x == "सत्तानवे")
    #expect(translator.translate(98, to: .hindi).x == "अट्ठानवे")
    #expect(translator.translate(99, to: .hindi).x == "निन्यानवे")
    #expect(translator.translate(100, to: .hindi).x == "एक सौ") // "सौ
    #expect(translator.translate(200, to: .hindi).x == "दो सौ") // "सौ
    #expect(translator.translate(250, to: .hindi).x == "दो सौ पचास") // दो सौ पचास
    #expect(translator.translate(300, to: .hindi).x == "तीन सौ") // "सौ
    #expect(translator.translate(352, to: .hindi).x == "तीन सौ बावन") // "सौ
    #expect(translator.translate(1000, to: .hindi).x == "एक हज़ार") // / एक सहस्र

    let temp1 = 10*1000
    #expect(translator.translate(temp1, to: .hindi).x == "दश हज़ार")

    let temp2 = 100*1000
    #expect(translator.translate(temp2, to: .hindi).x == "एक लाख") // 1 Lakh

    let temp3 = 10*100*1000
    #expect(translator.translate(temp3, to: .hindi).x == "दश लाख")
    #expect(translator.translate(1_000_000, to: .hindi).x == "दश लाख")
    #expect(translator.translate(1_000_500, to: .hindi).x == "दश लाख पांच सौ") // ? दश लाख पांच सौ

    let temp4 = 100*100*1000
    #expect(translator.translate(temp4, to: .hindi).x == "एक करोड़") // 1 Crore
    #expect(translator.translate(10_000_000, to: .hindi).x == "एक करोड़")

    let temp5 = 10*100*100_000
    #expect(translator.translate(temp5, to: .hindi).x == "दश करोड़")
    #expect(translator.translate(100_000_000, to: .hindi).x == "दश करोड़")

    let temp6 = 50*100*100_000
    #expect(translator.translate(temp6, to: .hindi).x == "पचास करोड़")
    #expect(translator.translate(500_000_000, to: .hindi).x == "पचास करोड़")

    let temp7 = 100*100*100*1000
    #expect(translator.translate(temp7, to: .hindi).x == "एक अरब") // 1 Arab
    #expect(translator.translate(1_000_000_000, to: .hindi).x == "एक अरब")

    let temp8 = 2*100*100*100*1000
    #expect(translator.translate(temp8, to: .hindi).x == "दो अरब")

    let temp9 = 2*100*100*100*1000+50*100*100_000
    #expect(translator.translate(temp9, to: .hindi).x == "दो अरब पचास करोड़") // दो अरब पचास करोड़
    #expect(translator.translate(2_500_000_000, to: .hindi).x == "दो अरब पचास करोड़") // दो अरब पांच सौ करोड़
    #expect(translator.translate(10_000_000_000, to: .hindi).x == "दश अरब")
    #expect(translator.translate(100_000_000_000, to: .hindi).x == "एक खरब") // एक सौ अरब
    #expect(translator.translate(-1, to: .hindi).x == "ऋण एक")
    #expect(translator.translate(1.3, to: .hindi).x == "एक दशमलव तीन")
}
