// Note: This file is automatically generated
//       It will be overwritten when testing

import Testing
@testable import NumberTranslator

@Test func RomanNumerals() {
    let translator = RomanNumeralsImplementation()
    #expect(translator.translate(0).x == "zero unknown")
    #expect(translator.translate(1).x == "I") // 1
    #expect(translator.translate(2).x == "II") // 1+1
    #expect(translator.translate(3).x == "III") // 1+1+1
    #expect(translator.translate(4).x == "IV") // 5-1
    #expect(translator.translate(5).x == "V") // 5
    #expect(translator.translate(6).x == "VI") // 5+1
    #expect(translator.translate(7).x == "VII") // 5+1+1
    #expect(translator.translate(8).x == "VIII") // 5+1+1+1
    #expect(translator.translate(9).x == "IX") // 10-1
    #expect(translator.translate(10).x == "X") // 10
    #expect(translator.translate(11).x == "XI") // 10+1
    #expect(translator.translate(12).x == "XII") // 10+1+1
    #expect(translator.translate(13).x == "XIII") // 10+1+1+1
    #expect(translator.translate(14).x == "XIV") // 10-1+5
    #expect(translator.translate(15).x == "XV") // 10+5
    #expect(translator.translate(16).x == "XVI") // 10+5+1
    #expect(translator.translate(17).x == "XVII") // 10+5+1+1
    #expect(translator.translate(18).x == "XVIII") // 10+5+1+1+1
    #expect(translator.translate(19).x == "XIX") // 10-1+10
    #expect(translator.translate(20).x == "XX") // 10+10
    #expect(translator.translate(21).x == "XXI") // 10+10+1
    #expect(translator.translate(22).x == "XXII") // 10+10+1+1
    #expect(translator.translate(23).x == "XXIII") // 10+10+1+1+1
    #expect(translator.translate(24).x == "XXIV") // 10+10-1+5
    #expect(translator.translate(25).x == "XXV") // 10+10+5
    #expect(translator.translate(26).x == "XXVI") // 10+10+5+1
    #expect(translator.translate(27).x == "XXVII") // 10+10+5+1+1
    #expect(translator.translate(28).x == "XXVIII") // 10+10+5+1+1+1
    #expect(translator.translate(29).x == "XXIX") // 10+10-1+10
    #expect(translator.translate(30).x == "XXX") // 10+10+10
    #expect(translator.translate(31).x == "XXXI") // 10+10+10+1
    #expect(translator.translate(32).x == "XXXII") // 10+10+10+1+1
    #expect(translator.translate(33).x == "XXXIII") // 10+10+10+1+1+1
    #expect(translator.translate(34).x == "XXXIV") // 10+10+10-1+5
    #expect(translator.translate(35).x == "XXXV") // 10+10+10+5
    #expect(translator.translate(36).x == "XXXVI") // 10+10+10+5+1
    #expect(translator.translate(37).x == "XXXVII") // 10+10+10+5+1+1
    #expect(translator.translate(38).x == "XXXVIII") // 10+10+10+5+1+1+1
    #expect(translator.translate(39).x == "XXXIX") // 10+10+10-1+10
    #expect(translator.translate(40).x == "XL") // -10+50
    #expect(translator.translate(41).x == "XLI") // -10+50+1
    #expect(translator.translate(42).x == "XLII") // -10+50+1+1
    #expect(translator.translate(43).x == "XLIII") // -10+50+1+1+1
    #expect(translator.translate(44).x == "XLIV") // -10+50-1+5
    #expect(translator.translate(45).x == "XLV") // -10+50+5
    #expect(translator.translate(46).x == "XLVI") // -10+50+5+1
    #expect(translator.translate(47).x == "XLVII") // -10+50+5+1+1
    #expect(translator.translate(48).x == "XLVIII") // -10+50+5+1+1+1
    #expect(translator.translate(49).x == "XLIX") // -10+50-1+10
    #expect(translator.translate(50).x == "L") // 50
    #expect(translator.translate(51).x == "LI") // 50+1
    #expect(translator.translate(52).x == "LII") // 50+1+1
    #expect(translator.translate(53).x == "LIII") // 50+1+1+1
    #expect(translator.translate(54).x == "LIV") // 50-1+5
    #expect(translator.translate(55).x == "LV") // 50+5
    #expect(translator.translate(56).x == "LVI") // 50+5+1
    #expect(translator.translate(57).x == "LVII") // 50+5+1+1
    #expect(translator.translate(58).x == "LVIII") // 50+5+1+1+1
    #expect(translator.translate(59).x == "LIX") // 50-1+10
    #expect(translator.translate(60).x == "LX") // 50+10
    #expect(translator.translate(61).x == "LXI") // 50+10+1
    #expect(translator.translate(62).x == "LXII") // 50+10+1+1
    #expect(translator.translate(63).x == "LXIII") // 50+10+1+1+1
    #expect(translator.translate(64).x == "LXIV") // 50+10-1+5
    #expect(translator.translate(65).x == "LXV") // 50+10+5
    #expect(translator.translate(66).x == "LXVI") // 50+10+5+1
    #expect(translator.translate(67).x == "LXVII") // 50+10+5+1+1
    #expect(translator.translate(68).x == "LXVIII") // 50+10+5+1+1+1
    #expect(translator.translate(69).x == "LXIX") // 50+10-1+10
    #expect(translator.translate(70).x == "LXX") // 50+10+10
    #expect(translator.translate(71).x == "LXXI") // 50+10+10+1
    #expect(translator.translate(72).x == "LXXII") // 50+10+10+1+1
    #expect(translator.translate(73).x == "LXXIII") // 50+10+10+1+1+1
    #expect(translator.translate(74).x == "LXXIV") // 50+10+10-1+5
    #expect(translator.translate(75).x == "LXXV") // 50+10+10+5
    #expect(translator.translate(76).x == "LXXVI") // 50+10+10+5+1
    #expect(translator.translate(77).x == "LXXVII") // 50+10+10+5+1+1
    #expect(translator.translate(78).x == "LXXVIII") // 50+10+10+5+1+1+1
    #expect(translator.translate(79).x == "LXXIX") // 50+10+10-1+10
    #expect(translator.translate(80).x == "LXXX") // 50+10+10+10
    #expect(translator.translate(81).x == "LXXXI") // 50+10+10+10+1
    #expect(translator.translate(82).x == "LXXXII") // 50+10+10+10+1+1
    #expect(translator.translate(83).x == "LXXXIII") // 50+10+10+10+1+1+1
    #expect(translator.translate(84).x == "LXXXIV") // 50+10+10+10-1+5
    #expect(translator.translate(85).x == "LXXXV") // 50+10+10+10+5
    #expect(translator.translate(86).x == "LXXXVI") // 50+10+10+10+5+1
    #expect(translator.translate(87).x == "LXXXVII") // 50+10+10+10+5+1+1
    #expect(translator.translate(88).x == "LXXXVIII") // 50+10+10+10+5+1+1+1
    #expect(translator.translate(89).x == "LXXXIX") // 50+10+10+10-1+10
    #expect(translator.translate(90).x == "XC") // 100-10
    #expect(translator.translate(91).x == "XCI") // 100-10+1
    #expect(translator.translate(92).x == "XCII") // 100-10+1+1
    #expect(translator.translate(93).x == "XCIII") // 100-10+1+1+1
    #expect(translator.translate(94).x == "XCIV") // 100-10-1+5
    #expect(translator.translate(95).x == "XCV") // 100-10+5
    #expect(translator.translate(96).x == "XCVI") // 100-10+5+1
    #expect(translator.translate(97).x == "XCVII") // 100-10+5+1+1
    #expect(translator.translate(98).x == "XCVIII") // 100-10+5+1+1+1
    #expect(translator.translate(99).x == "XCIX") // 100-10-1+10
    #expect(translator.translate(100).x == "C") // 100
    #expect(translator.translate(101).x == "CI")
    #expect(translator.translate(160).x == "CLX")
    #expect(translator.translate(200).x == "CC") // 100+100
    #expect(translator.translate(207).x == "CCVII")
    #expect(translator.translate(222).x == "CCXXII")
    #expect(translator.translate(246).x == "CCXLVI")
    #expect(translator.translate(300).x == "CCC") // 100+100+100
    #expect(translator.translate(333).x == "CCCXXXIII")
    #expect(translator.translate(400).x == "CD") // 500-100
    #expect(translator.translate(444).x == "CDXLIV")
    #expect(translator.translate(500).x == "D") // 500
    #expect(translator.translate(555).x == "DLV")
    #expect(translator.translate(600).x == "DC") // 500+100
    #expect(translator.translate(654).x == "DCLIV")
    #expect(translator.translate(700).x == "DCC") // 500+100+100
    #expect(translator.translate(777).x == "DCCLXXVII")
    #expect(translator.translate(789).x == "DCCLXXXIX")
    #expect(translator.translate(800).x == "DCCC") // 500+100+100+100
    #expect(translator.translate(888).x == "DCCCLXXXVIII")
    #expect(translator.translate(900).x == "CM") // 1000-100
    #expect(translator.translate(1000).x == "M") // 1000
    #expect(translator.translate(1001).x == "MI")
    #expect(translator.translate(1_009).x == "MIX")
    #expect(translator.translate(1_066).x == "MLXVI")
    #expect(translator.translate(1_222).x == "MCCXXII")
    #expect(translator.translate(1_444).x == "MCDXLIV")
    #expect(translator.translate(1_666).x == "MDCLXVI")
    #expect(translator.translate(2_000).x == "MM")
    #expect(translator.translate(2_421).x == "MMCDXXI")
    #expect(translator.translate(2_999).x == "MMCMXCIX")
    #expect(translator.translate(3_000).x == "MMM")
    #expect(translator.translate(3_500).x == "MMMD")
    #expect(translator.translate(3_999).x == "MMMCMXCIX")
    #expect(translator.translate(5_000).x == "V OVERLINE")
    #expect(translator.translate(10_000).x == "X OVERLINE")
    #expect(translator.translate(19876).x == "XIX OVERLINE DCCCLXXVI")
    #expect(translator.translate(36_000).x == "XXXVI OVERLINE")
    #expect(translator.translate(50_000).x == "L OVERLINE")
    #expect(translator.translate(54321).x == "LIV OVERLINE CCCXXI")
    #expect(translator.translate(87654).x == "LXXXVII OVERLINE DCLIV")
    #expect(translator.translate(98765).x == "XCVIII OVERLINE DCCLXV")
    #expect(translator.translate(100_000).x == "C OVERLINE")
    #expect(translator.translate(123_456).x == "CXXIII OVERLINE CDLVI")
    #expect(translator.translate(300000).x == "CCC OVERLINE")
    #expect(translator.translate(500_000).x == "D OVERLINE")
    #expect(translator.translate(987_654).x == "CMLXXXVII OVERLINE DCLIV")
    #expect(translator.translate(1_000_000).x == "M OVERLINE")
    #expect(translator.translate(-1).x == "negative not allowed")
}
