// Note: This file is automatically generated by the python script Tests/testsFromGroundtruth.py
//       Running this script will be overwrite any changes you make to this file

import Testing
@testable import NumberTranslator

@Test func Russian() {
    let translator = NumberTranslator()
    // https: lingopie.com/blog/your-ultimate-guide-to-russian-numbers-how-to-count-in-russian/
    #expect(translator.translate(0, to: .russian).x == "ноль")
    #expect(translator.translate(1, to: .russian).x == "один")
    #expect(translator.translate(2, to: .russian).x == "два")
    #expect(translator.translate(3, to: .russian).x == "три")
    #expect(translator.translate(4, to: .russian).x == "четыре")
    #expect(translator.translate(5, to: .russian).x == "пять")
    #expect(translator.translate(6, to: .russian).x == "шесть")
    #expect(translator.translate(7, to: .russian).x == "семь")
    #expect(translator.translate(8, to: .russian).x == "восемь")
    #expect(translator.translate(9, to: .russian).x == "девять")
    #expect(translator.translate(10, to: .russian).x == "десять")
    #expect(translator.translate(11, to: .russian).x == "одиннадцать")
    #expect(translator.translate(12, to: .russian).x == "двенадцать")
    #expect(translator.translate(13, to: .russian).x == "тринадцать")
    #expect(translator.translate(14, to: .russian).x == "четырнадцать")
    #expect(translator.translate(15, to: .russian).x == "пятнадцать")
    #expect(translator.translate(16, to: .russian).x == "шестнадцать")
    #expect(translator.translate(17, to: .russian).x == "семнадцать")
    #expect(translator.translate(18, to: .russian).x == "восемнадцать")
    #expect(translator.translate(19, to: .russian).x == "девятнадцать")
    #expect(translator.translate(20, to: .russian).x == "двадцать")
    #expect(translator.translate(23, to: .russian).x == "двадцать три")
    #expect(translator.translate(30, to: .russian).x == "тридцать")
    #expect(translator.translate(33, to: .russian).x == "тридцать три")
    #expect(translator.translate(40, to: .russian).x == "сорок")
    #expect(translator.translate(50, to: .russian).x == "пятьдесят")
    #expect(translator.translate(60, to: .russian).x == "шестьдесят")
    #expect(translator.translate(70, to: .russian).x == "семьдесят")
    #expect(translator.translate(80, to: .russian).x == "восемьдесят")
    #expect(translator.translate(90, to: .russian).x == "девяносто")
    #expect(translator.translate(100, to: .russian).x == "стo")
    #expect(translator.translate(101, to: .russian).x == "стo один")
    #expect(translator.translate(111, to: .russian).x == "стo одиннадцать")
    #expect(translator.translate(131, to: .russian).x == "стo тридцать один")
    #expect(translator.translate(200, to: .russian).x == "двести")
    #expect(translator.translate(245, to: .russian).x == "двести сорок пять")
    #expect(translator.translate(300, to: .russian).x == "триста")
    #expect(translator.translate(375, to: .russian).x == "триста семьдесят пять")
    #expect(translator.translate(400, to: .russian).x == "четыреста")
    #expect(translator.translate(500, to: .russian).x == "пятьсот")
    #expect(translator.translate(600, to: .russian).x == "шестьсот")
    #expect(translator.translate(700, to: .russian).x == "семьсот")
    #expect(translator.translate(800, to: .russian).x == "восемьсот")
    #expect(translator.translate(900, to: .russian).x == "девятьсот")
    #expect(translator.translate(999, to: .russian).x == "девятьсот девяносто девять")
    #expect(translator.translate(1_000, to: .russian).x == "тысяча")
    #expect(translator.translate(1_348, to: .russian).x == "тысяча триста сорок восемь")
    #expect(translator.translate(1_534, to: .russian).x == "тысяча пятьсот тридцать четыре")
    #expect(translator.translate(2_000, to: .russian).x == "две тысячи")
    #expect(translator.translate(2_345, to: .russian).x == "две тысячи триста сорок пять")
    #expect(translator.translate(3_000, to: .russian).x == "три тысячи")
    #expect(translator.translate(4_000, to: .russian).x == "четыре тысячи")
    #expect(translator.translate(5_000, to: .russian).x == "пять тысяч")
    #expect(translator.translate(6_000, to: .russian).x == "шесть тысяч")
    #expect(translator.translate(7_000, to: .russian).x == "семь тысяч")
    #expect(translator.translate(8_000, to: .russian).x == "восемь тысяч")
    #expect(translator.translate(8_343, to: .russian).x == "восемь тысяч триста сорок три")
    #expect(translator.translate(9_000, to: .russian).x == "девять тысяч")
    #expect(translator.translate(9_203, to: .russian).x == "девять тысяч двести три")
    #expect(translator.translate(9_999, to: .russian).x == "девять тысяч девятьсот девяносто девять")
    #expect(translator.translate(10_000, to: .russian).x == "десять тысяч")
    #expect(translator.translate(11_000, to: .russian).x == "одиннадцать тысяч")
    #expect(translator.translate(11_111, to: .russian).x == "одиннадцать тысяч стo одиннадцать")
    #expect(translator.translate(12_000, to: .russian).x == "двенадцать тысяч")
    #expect(translator.translate(19_000, to: .russian).x == "девятнадцать тысяч")
    #expect(translator.translate(20_000, to: .russian).x == "двадцать тысяч")
    #expect(translator.translate(21_000, to: .russian).x == "двадцать одна тысяча")
    #expect(translator.translate(22_000, to: .russian).x == "двадцать две тысячи")
    #expect(translator.translate(23_000, to: .russian).x == "двадцать три тысячи")
    #expect(translator.translate(24_000, to: .russian).x == "двадцать четыре тысячи")
    #expect(translator.translate(25_000, to: .russian).x == "двадцать пять тысяч")
    #expect(translator.translate(23_456, to: .russian).x == "двадцать три тысячи четыреста пятьдесят шесть")
    #expect(translator.translate(41_000, to: .russian).x == "сорок одна тысяча")
    #expect(translator.translate(99_999, to: .russian).x == "девяносто девять тысяч девятьсот девяносто девять")
    #expect(translator.translate(100_000, to: .russian).x == "стo тысяч")
    #expect(translator.translate(101_000, to: .russian).x == "стo одна тысяча")
    #expect(translator.translate(101_111, to: .russian).x == "стo одна тысяча стo одиннадцать")
    #expect(translator.translate(234_567, to: .russian).x == "двести тридцать четыре тысячи пятьсот шестьдесят семь")
    #expect(translator.translate(243_382, to: .russian).x == "двести сорок три тысячи триста восемьдесят два")
    #expect(translator.translate(999_999, to: .russian).x == "девятьсот девяносто девять тысяч девятьсот девяносто девять")
    #expect(translator.translate(101_101_101, to: .russian).x == "стo один миллион стo одна тысяча стo один")
    #expect(translator.translate(234_567_890, to: .russian).x == "двести тридцать четыре миллиона пятьсот шестьдесят семь тысяч восемьсот девяносто")
    #expect(translator.translate(999_999_999, to: .russian).x == "девятьсот девяносто девять миллионов девятьсот девяносто девять тысяч девятьсот девяносто девять")
    #expect(translator.translate(1_000_000_000, to: .russian).x == "один миллиард")
    #expect(translator.translate(2_000_000_000, to: .russian).x == "два миллиарда")
    #expect(translator.translate(10_000_000_000, to: .russian).x == "десять миллиардов")
    #expect(translator.translate(1_000_000_000_000, to: .russian).x == "один триллион")
    #expect(translator.translate(2_000_000_000_000, to: .russian).x == "два триллиона")
    #expect(translator.translate(10_000_000_000_000, to: .russian).x == "десять триллионов")
    // unclear:
    // 1_000_000 один миллион
    // 2_000_000 два миллиона
    // 3_000_000 три миллиона
    // 4_000_000 четыре миллиона
    // 5_000_000 пять миллионов
    // 6_000_000 шесть миллионов
    // 7_000_000 семь миллионов
    // 8_000_000 восемь миллионов
    // 9_000_000 девять миллионов
    // 10_000_000 десять миллионов
    // 100_000_000 стo миллионов
    // 22_000 "двадцать две тысячи"  "двадцать два тысячи"
    // 21_000 "двадцать одна тысяча" "двадцать один тысяча"
    // 41_000 "сорок одна тысяча"    "сорок один тысяча"
    // 10_000_000_000_000  "дксять триллионов" "десять триллионов"
}
