// Note: This file is automatically generated by the python script Tests/testsFromGroundtruth.py
//       Running this script will be overwrite any changes you make to this file

import Testing
@testable import NumberTranslator

@Test func ThaiNumerals() {
    let translator = NumberTranslator()
    #expect(translator.translate(0, to: .thaiNumerals).x == "๐")
    #expect(translator.translate(1, to: .thaiNumerals).x == "๑")
    #expect(translator.translate(2, to: .thaiNumerals).x == "๒")
    #expect(translator.translate(3, to: .thaiNumerals).x == "๓")
    #expect(translator.translate(4, to: .thaiNumerals).x == "๔")
    #expect(translator.translate(5, to: .thaiNumerals).x == "๕")
    #expect(translator.translate(6, to: .thaiNumerals).x == "๖")
    #expect(translator.translate(7, to: .thaiNumerals).x == "๗")
    #expect(translator.translate(8, to: .thaiNumerals).x == "๘")
    #expect(translator.translate(9, to: .thaiNumerals).x == "๙")
    #expect(translator.translate(10, to: .thaiNumerals).x == "๑๐")
    #expect(translator.translate(11, to: .thaiNumerals).x == "๑๑")
    #expect(translator.translate(12, to: .thaiNumerals).x == "๑๒")
    #expect(translator.translate(13, to: .thaiNumerals).x == "๑๓")
    #expect(translator.translate(14, to: .thaiNumerals).x == "๑๔")
    #expect(translator.translate(114, to: .thaiNumerals).x == "๑๑๔")
    #expect(translator.translate(114.7, to: .thaiNumerals).x == "๑๑๔.๗")
    #expect(translator.translate(1_147, to: .thaiNumerals).x == "๑๑๔๗")
    #expect(translator.translate(1_000, to: .thaiNumerals).x == "๑๐๐๐")
    #expect(translator.translate(-1, to: .thaiNumerals).x == "-๑")
    #expect(translator.translate(1.3, to: .thaiNumerals).x == "๑.๓")
}
