// Note: This file is automatically generated
//       It will be overwritten when testing

import Testing
@testable import NumberTranslator

@Test func ThaiNumerals() {
    let translator = ThaiNumeralsImplementation()
    #expect(translator.translate(0).x == "๐")
    #expect(translator.translate(1).x == "๑")
    #expect(translator.translate(2).x == "๒")
    #expect(translator.translate(3).x == "๓")
    #expect(translator.translate(4).x == "๔")
    #expect(translator.translate(5).x == "๕")
    #expect(translator.translate(6).x == "๖")
    #expect(translator.translate(7).x == "๗")
    #expect(translator.translate(8).x == "๘")
    #expect(translator.translate(9).x == "๙")
    #expect(translator.translate(10).x == "๑๐")
    #expect(translator.translate(11).x == "๑๑")
    #expect(translator.translate(12).x == "๑๒")
    #expect(translator.translate(13).x == "๑๓")
    #expect(translator.translate(14).x == "๑๔")
    #expect(translator.translate(114).x == "๑๑๔")
    #expect(translator.translate(114.7).x == "๑๑๔.๗")
    #expect(translator.translate(1_147).x == "๑๑๔๗")
    #expect(translator.translate(1_000).x == "๑๐๐๐")
    #expect(translator.translate(-1).x == "-๑")
    #expect(translator.translate(1.3).x == "๑.๓")
}
