// Note: This file is automatically generated
//       It will be overwritten when testing

import Testing
@testable import NumberTranslator

@Test func traditionalChinese() {
    let translator = NumberTranslator()
    #expect(translator.translate(0, to: .traditionalChinese).x == "零")
    #expect(translator.translate(10_000, to: .traditionalChinese).x == "一萬")
    #expect(translator.translate(789_0298, to: .traditionalChinese).x == "七百 八十九萬 零二百 九十八")
}
